-- https://school.programmers.co.kr/learn/courses/30/lessons/144856

SELECT
    AUTHOR_ID
    , AUTHOR_NAME
    , CATEGORY
    , SUM(PRICE*SALES) TOTAL_SALES
FROM
    BOOK_SALES S
    JOIN BOOK B USING(BOOK_ID)
    JOIN AUTHOR A USING(AUTHOR_ID)
WHERE
    YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 1
GROUP BY
    AUTHOR_ID
    , CATEGORY
ORDER BY
    AUTHOR_ID ASC
    , CATEGORY DESC
;