-- https://school.programmers.co.kr/learn/courses/30/lessons/131534
WITH JOINED_2021 AS (
    SELECT COUNT(*) NUM
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT
    YEAR(SALES_DATE) YEAR
    , MONTH(SALES_DATE) MONTH
    , COUNT(DISTINCT USER_ID) PURCHASED_USERS
    , ROUND(COUNT(DISTINCT USER_ID)/(SELECT NUM FROM JOINED_2021), 1) PURCHASED_RATIO
FROM
    USER_INFO U
    JOIN ONLINE_SALE O USING(USER_ID)
WHERE
    YEAR(JOINED) = 2021
GROUP BY
    YEAR(SALES_DATE)
    , MONTH(SALES_DATE)
ORDER BY
    1, 2
;