-- https://school.programmers.co.kr/learn/courses/30/lessons/131117
SELECT
    PRODUCT_ID
    , PRODUCT_NAME
    , SUM(AMOUNT*PRICE) TOTAL_SALES
FROM
    FOOD_PRODUCT P
    JOIN FOOD_ORDER USING(PRODUCT_ID)
WHERE
    YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY
    PRODUCT_ID
ORDER BY
    3 DESC
    , 1 ASC
;